### ISSUE TITLE
Unable to run dsprite_FactorVAE.sh

### ISSUE THREAD

**Issue by AlexanderZhujiageng** [amir-abdi/disentanglement-pytorch#66]
When I trying to run scripts/dsprite_FactorVAE.sh
The following error happened:
`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1000, 2]], which is output 0 of TBackward, is at version 2; expected version 1 instead.`

Which seems the problem with the discriminator. But even if I changed the inplace flag in the `nn.LeakyReLU(0.2,inplace=False)`, the problem still exsits

**Comment by amir-abdi** [comment]
This has probably happened because I missed to lock the version of pytorch and the above is due to a new feature in the newest verison of pytorch.

Since I haven't updated the library for the past year (since NeurIPS 2019), I have now updated the `requirements.txt` to include the torch and torchvision verisons.

Let me know if that did not resolve your problem.

**Comment by AlexanderZhujiageng** [comment]
Yes, this solved my problem. But I am still curious why this happened in the new pytorch version. 
Anyway, I will figure it out, it solved quesiton right now.
Thanks a lot!
